/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import NEGOCIO.Administrador;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelcy Velasco
 */
public class frmLogin extends javax.swing.JFrame {
    Toolkit t;
    Dimension screenSize;
    ImageIcon fot;
    ImageIcon fot2;
    Icon icono;
    Icon icono2;
    
    
    
    


    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        
        initComponents();
        setIcon();
        this.lblNotificacionDatos.setVisible(false);
        
        setLocationRelativeTo(frmLogin.this);
        setTitle("COFFE SOFT - INGRESO");
        this.setExtendedState(frmLogin.MAXIMIZED_BOTH);
        t = Toolkit.getDefaultToolkit();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        
        fot = new ImageIcon("src/PRESENTACION/imagenes/logoFinal2.png");
        icono = new ImageIcon(fot.getImage().getScaledInstance(this.lblLogo.getWidth(), this.lblLogo.getHeight(), Image.SCALE_DEFAULT));
        this.lblLogo.setIcon(icono);
        //this.repaint();
        
        fot2 = new ImageIcon("src/PRESENTACION/imagenes/blanco.png");
        icono2 = new ImageIcon(fot2.getImage().getScaledInstance(this.lblFondo.getWidth(), this.lblFondo.getHeight(), Image.SCALE_DEFAULT));
        this.lblFondo.setIcon(icono2);
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblUsuario1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblNotificacionDatos = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasenia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblContrasenia.setText("Contraseña:");
        getContentPane().add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 300, -1));

        txtContrasenia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 300, -1));

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/enter.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, 70));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 140, 70));

        lblUsuario1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario1.setText("Usuario:");
        getContentPane().add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 4, 390, 320));

        lblNotificacionDatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNotificacionDatos.setForeground(new java.awt.Color(255, 0, 0));
        lblNotificacionDatos.setText("Usuario/Contraseña Incorrectos");
        getContentPane().add(lblNotificacionDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, -1, -1));

        lblFondo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
        int verificar = verificarCampos();
        this.lblNotificacionDatos.setVisible(false);
        String usuario = this.txtUsuario.getText();
        char passArray[] = txtContrasenia.getPassword();
        String clave = new String(passArray);
        int verificar2 = 0;
        
        if(verificar  == 0 ){
            
              
            try{
                Administrador miAdmin = new Administrador(usuario, clave);
                ArrayList<Object[]> datos = miAdmin.ingresar();    
                Object[] columnas = datos.get(1);
                String d1 = Arrays.toString(columnas);
                verificar2 = 1;
            }
            catch(Exception ne)
            {
                //JOptionPane.showMessageDialog(this, "Se presento la excepcion:   "+ ne.getMessage() );
                this.txtUsuario.setText("");
                this.txtContrasenia.setText("");
                usuario = "";
                clave = "";
                this.lblNotificacionDatos.setVisible(true);
                verificar2 = 2;
            }
            finally{

            }
            
            
            if(verificar2 == 1){
                frmPrincipal myFrmPrincipal = new frmPrincipal();
                myFrmPrincipal.setVisible(true);
                dispose();
            }
                
        }else{
            JOptionPane.showMessageDialog(this, "Falta datos!!");
            
        }
        
        
            
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        dispose();
        setDefaultCloseOperation(frmLogin.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnSalirMouseClicked
    
    private int verificarCampos(){
        int retVerificar = 0;
        
        char passArray[] = txtContrasenia.getPassword();
        String clave = new String(passArray);
        
        if(this.txtUsuario.getText().length()==0)
            retVerificar = 1;
        if(clave.length() == 0)
            retVerificar = 1;
        
        
        return retVerificar;    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNotificacionDatos;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconProgram.png")));
    }
}
