/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

import NEGOCIO.Administrador;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author SGTheDreamer
 */
public class frmPrincipal extends javax.swing.JFrame {
    Toolkit t;
    Dimension screenSize;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.PanelActualizarDatos.setVisible(false);
        this.PanelActualizarDatos.setEnabled(false);
        this.lblNotificacionDatos.setVisible(false);
        this.txtUsuarioNuevo.setEnabled(false);
        this.txtContraseniaNueva.setEnabled(false);
        setIcon();
        setLocationRelativeTo(frmPrincipal.this);
        setTitle("COFFE SOFT");
        this.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);
        t = Toolkit.getDefaultToolkit();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        
        ImageIcon fot = new ImageIcon("src/PRESENTACION/imagenes/fondoPrincipal.jpg");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(this.lblImagenPrincipal.getWidth(), this.lblImagenPrincipal.getHeight(), Image.SCALE_DEFAULT));
        this.lblImagenPrincipal.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        btnGPersonas = new javax.swing.JButton();
        btnGMateriales = new javax.swing.JButton();
        btnGLotes = new javax.swing.JButton();
        btnGActividades = new javax.swing.JButton();
        btnGReportes = new javax.swing.JButton();
        btnGraficos = new javax.swing.JButton();
        PanelActualizarDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        lblContraseniaActual = new javax.swing.JLabel();
        lblUsuarioNuevo = new javax.swing.JLabel();
        lblContraseniaNueva = new javax.swing.JLabel();
        txtUsuarioActual = new javax.swing.JTextField();
        txtContraseniaActual = new javax.swing.JTextField();
        txtUsuarioNuevo = new javax.swing.JTextField();
        txtContraseniaNueva = new javax.swing.JTextField();
        btnActualizarDatos = new javax.swing.JButton();
        btnCancelarActDatos = new javax.swing.JButton();
        lblNotificacionDatos = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        lblImagenPrincipal = new javax.swing.JLabel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuActuaizarDatos = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuGestion = new javax.swing.JMenu();
        menuPersonas = new javax.swing.JMenuItem();
        menuEventos = new javax.swing.JMenuItem();
        menuMateriales = new javax.swing.JMenuItem();
        menuLotes = new javax.swing.JMenuItem();
        menuReporte = new javax.swing.JMenu();
        menuGReporte = new javax.swing.JMenuItem();
        menuGraficos = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenuItem3.setText("jMenuItem3");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGPersonas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGPersonas.setText("G. Personas");
        btnGPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGPersonasMouseClicked(evt);
            }
        });
        getContentPane().add(btnGPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 90));

        btnGMateriales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGMateriales.setText("G. Materiales");
        btnGMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGMaterialesMouseClicked(evt);
            }
        });
        getContentPane().add(btnGMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 90));

        btnGLotes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGLotes.setText("G. Lotes");
        btnGLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGLotesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 90));

        btnGActividades.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGActividades.setText("G. Actividades");
        btnGActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGActividadesMouseClicked(evt);
            }
        });
        getContentPane().add(btnGActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 90));

        btnGReportes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGReportes.setText("Reportes");
        btnGReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGReportesMouseClicked(evt);
            }
        });
        getContentPane().add(btnGReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 200, 90));

        btnGraficos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGraficos.setText("Graficos");
        getContentPane().add(btnGraficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 200, 90));

        PanelActualizarDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Actualizar Datos ");
        PanelActualizarDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        lblUsuarioActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuarioActual.setText("Usuario actual:");
        PanelActualizarDatos.add(lblUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lblContraseniaActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContraseniaActual.setText("Contraseña actual:");
        PanelActualizarDatos.add(lblContraseniaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        lblUsuarioNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuarioNuevo.setText("Usuario nuevo:");
        PanelActualizarDatos.add(lblUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        lblContraseniaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContraseniaNueva.setText("Contraseña nueva:");
        PanelActualizarDatos.add(lblContraseniaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        txtUsuarioActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PanelActualizarDatos.add(txtUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 240, -1));

        txtContraseniaActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PanelActualizarDatos.add(txtContraseniaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 240, -1));

        txtUsuarioNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PanelActualizarDatos.add(txtUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 240, -1));

        txtContraseniaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PanelActualizarDatos.add(txtContraseniaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 240, -1));

        btnActualizarDatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnActualizarDatos.setText("Actualizar");
        btnActualizarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarDatosMouseClicked(evt);
            }
        });
        PanelActualizarDatos.add(btnActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        btnCancelarActDatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelarActDatos.setText("Cancelar");
        btnCancelarActDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarActDatosMouseClicked(evt);
            }
        });
        PanelActualizarDatos.add(btnCancelarActDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        lblNotificacionDatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNotificacionDatos.setForeground(new java.awt.Color(255, 0, 0));
        lblNotificacionDatos.setText("Usuario/Contraseña Incorrectos");
        PanelActualizarDatos.add(lblNotificacionDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        PanelActualizarDatos.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        getContentPane().add(PanelActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 670, 530));
        getContentPane().add(lblImagenPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        menuActuaizarDatos.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuActuaizarDatos.setText("Actualizar Datos");
        menuActuaizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActuaizarDatosActionPerformed(evt);
            }
        });
        menuArchivo.add(menuActuaizarDatos);

        menuSalir.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuSalir.setText("Cerrar Sesión");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        menuBarPrincipal.add(menuArchivo);

        menuGestion.setText("Gestion");
        menuGestion.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        menuPersonas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPersonas.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuPersonas.setText("Personas");
        menuPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPersonasActionPerformed(evt);
            }
        });
        menuGestion.add(menuPersonas);

        menuEventos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuEventos.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuEventos.setText("Actividades");
        menuEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEventosActionPerformed(evt);
            }
        });
        menuGestion.add(menuEventos);

        menuMateriales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuMateriales.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuMateriales.setText("Materiales");
        menuMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterialesActionPerformed(evt);
            }
        });
        menuGestion.add(menuMateriales);

        menuLotes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuLotes.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuLotes.setText("Lotes");
        menuLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLotesActionPerformed(evt);
            }
        });
        menuGestion.add(menuLotes);

        menuBarPrincipal.add(menuGestion);

        menuReporte.setText("Reportes");
        menuReporte.setActionCommand("");
        menuReporte.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        menuGReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuGReporte.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuGReporte.setText("Generar Reporte");
        menuGReporte.setToolTipText("");
        menuGReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGReporteActionPerformed(evt);
            }
        });
        menuReporte.add(menuGReporte);

        menuGraficos.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuGraficos.setText("Generar Gráficos Gastos");
        menuGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGraficosActionPerformed(evt);
            }
        });
        menuReporte.add(menuGraficos);

        menuBarPrincipal.add(menuReporte);

        menuHelp.setText("Help");
        menuHelp.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        menuSobre.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuHelp.add(menuSobre);

        menuBarPrincipal.add(menuHelp);

        setJMenuBar(menuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPersonasActionPerformed
        // TODO add your handling code here:
        frmRegistrarEmpleado myRegistrarEmpleado = new frmRegistrarEmpleado();
        myRegistrarEmpleado.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuPersonasActionPerformed

    private void menuEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEventosActionPerformed
        // TODO add your handling code here:
        frmEvento myEvento = new frmEvento();
        myEvento.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuEventosActionPerformed

    private void menuMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterialesActionPerformed
        // TODO add your handling code here:
        frmRegistroInsumo myInsumo = new frmRegistroInsumo();
        myInsumo.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuMaterialesActionPerformed

    private void menuLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLotesActionPerformed
        // TODO add your handling code here:
        frmRegistrarLote myLote = new frmRegistrarLote();
        myLote.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_menuLotesActionPerformed

    private void menuGReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGReporteActionPerformed
        // TODO add your handling code here:
        frmReporte myReporte = new frmReporte();
        myReporte.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuGReporteActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        frmLogin myLogin = new frmLogin();
        myLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnGPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGPersonasMouseClicked
        // TODO add your handling code here:
        frmRegistrarEmpleado myRegistrarEmpleado = new frmRegistrarEmpleado();
        myRegistrarEmpleado.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGPersonasMouseClicked

    private void menuGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGraficosActionPerformed
        // TODO add your handling code here:
        frmGraficos myGrafico = new frmGraficos();
        myGrafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuGraficosActionPerformed

    private void btnGMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGMaterialesMouseClicked
       // TODO add your handling code here:
        frmRegistroInsumo myInsumo = new frmRegistroInsumo();
        myInsumo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGMaterialesMouseClicked

    private void btnGLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGLotesActionPerformed
        // TODO add your handling code here:
        frmRegistrarLote myLote = new frmRegistrarLote();
        myLote.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGLotesActionPerformed

    private void btnGActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGActividadesMouseClicked
        // TODO add your handling code here:
        frmEvento myEvento = new frmEvento();
        myEvento.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGActividadesMouseClicked

    private void btnGReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGReportesMouseClicked
        // TODO add your handling code here:
        frmReporte myReporte = new frmReporte();
        myReporte.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGReportesMouseClicked

    private void btnActualizarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDatosMouseClicked
        // TODO add your handling code here:

        int verificar = verificarCampos(this.txtUsuarioNuevo, this.txtContraseniaNueva);
        
        if(verificar  == 0 ){
            String userNew = this.txtUsuarioNuevo.getText();
            String passNew = this.txtContraseniaNueva.getText();
            String userAct = this.txtUsuarioActual.getText();
              
            
            Administrador miAdmin = new Administrador(userNew, passNew);
            int res = miAdmin.actualizarDatos(userAct);
            
            if (res == 1) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados");
                frmPrincipal myPrincipal = new frmPrincipal();
                myPrincipal.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Datos NO Actualizados");
            }
                
        }else{
            JOptionPane.showMessageDialog(this, "Falta datos!!");
        }  
    }//GEN-LAST:event_btnActualizarDatosMouseClicked

    private void menuActuaizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActuaizarDatosActionPerformed
        // TODO add your handling code here:
        this.PanelActualizarDatos.setVisible(true);
        this.PanelActualizarDatos.setEnabled(true);
    }//GEN-LAST:event_menuActuaizarDatosActionPerformed

    private void btnCancelarActDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarActDatosMouseClicked
        // TODO add your handling code here:
        this.PanelActualizarDatos.setVisible(false);
        this.PanelActualizarDatos.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActDatosMouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
        
        int verificar = verificarCampos(this.txtUsuarioActual, this.txtContraseniaActual);
        this.lblNotificacionDatos.setVisible(false);
        
        int verificar2 = 0;
        
        if(verificar  == 0 ){
            String userAct = this.txtUsuarioActual.getText();
            String passAct = this.txtContraseniaActual.getText();
              
            try{
                Administrador miAdmin = new Administrador(userAct, passAct);
                ArrayList<Object[]> datos = miAdmin.ingresar();    
                Object[] columnas = datos.get(1);
                String d1 = Arrays.toString(columnas);
                verificar2 = 1;
            }
            catch(Exception ne)
            {
                //JOptionPane.showMessageDialog(this, "Se presento la excepcion:   "+ ne.getMessage() );
                this.txtUsuarioActual.setText("");
                this.txtContraseniaActual.setText("");
                userAct = "";
                passAct = "";
                this.lblNotificacionDatos.setVisible(true);
                this.txtUsuarioNuevo.setEnabled(false);
                this.txtContraseniaNueva.setEnabled(false);
                verificar2 = 2;
            }
            finally{
                
            }
            
            
            if(verificar2 == 1){
                this.txtUsuarioNuevo.setEnabled(true);
                this.txtContraseniaNueva.setEnabled(true);
                this.txtContraseniaActual.setEnabled(false);
                this.txtUsuarioActual.setEnabled(false);
            }
                
        }else{
            JOptionPane.showMessageDialog(this, "Falta datos!!");
            
        }
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSobreActionPerformed
    
    private int verificarCampos(JTextField user, JTextField pass){
        int retVerificar = 0;
        
        
        if(user.getText().length()==0)
            retVerificar = 1;
        if(pass.getText().length() == 0)
            retVerificar = 1;
        return retVerificar;    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelActualizarDatos;
    private javax.swing.JButton btnActualizarDatos;
    private javax.swing.JButton btnCancelarActDatos;
    private javax.swing.JButton btnGActividades;
    private javax.swing.JButton btnGLotes;
    private javax.swing.JButton btnGMateriales;
    private javax.swing.JButton btnGPersonas;
    private javax.swing.JButton btnGReportes;
    private javax.swing.JButton btnGraficos;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblContraseniaActual;
    private javax.swing.JLabel lblContraseniaNueva;
    private javax.swing.JLabel lblImagenPrincipal;
    private javax.swing.JLabel lblNotificacionDatos;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JLabel lblUsuarioNuevo;
    private javax.swing.JMenuItem menuActuaizarDatos;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenuItem menuEventos;
    private javax.swing.JMenuItem menuGReporte;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenuItem menuGraficos;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuLotes;
    private javax.swing.JMenuItem menuMateriales;
    private javax.swing.JMenuItem menuPersonas;
    private javax.swing.JMenu menuReporte;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JTextField txtContraseniaActual;
    private javax.swing.JTextField txtContraseniaNueva;
    private javax.swing.JTextField txtUsuarioActual;
    private javax.swing.JTextField txtUsuarioNuevo;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconProgram.png")));
    }
}
