package PRESENTACION;

import NEGOCIO.Administrador;


import java.text.SimpleDateFormat;
import NEGOCIO.GenerarReporte;


import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;

import com.itextpdf.*;
import java.io.FileOutputStream;
import java.text.DecimalFormat;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;
import java.io.FileOutputStream;
import java.io.*;
import java.util.*;
import java.sql.*;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

/**
 *
 * @author Yeison Caicedo- Andres Garzón
 */
public class frmReporte extends javax.swing.JFrame {

    

    private final String FILE1 = "F:/pdf/ReporteLotes.pdf";
    private final String FILE2 = "F:/pdf/ReporteEmpleados.pdf";
    private final String FILE3 = "F:/pdf/ReporteFinal.pdf";

    public static String dataOne;
    public static String nameOne;
    public static String descOne;
    public static String costOne;
    public static String[] celdasInforme;
    static int tamano;
    public static int j;

    private final Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private final Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private final Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private final Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
    public static PdfPTable tablaLotes;

    /**
     * Creates new form frmGenerarReporte
     */
    public frmReporte() {
        initComponents();
        setIcon2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblParametros = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        cldFechaInicio = new com.toedter.calendar.JDateChooser();
        cldFechaFin = new com.toedter.calendar.JDateChooser();
        btnHome = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        lblGenerarReporte1 = new javax.swing.JLabel();
        cbxTipoInforme = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblParametros.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblParametros.setForeground(new java.awt.Color(255, 255, 255));
        lblParametros.setText("Tipo de Informe : ");
        getContentPane().add(lblParametros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setText("Fecha Inicio:");
        getContentPane().add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaFin.setText("Fecha Fin:");
        getContentPane().add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        cldFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cldFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 200, 30));

        cldFechaFin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cldFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 200, 30));

        btnHome.setBackground(new java.awt.Color(207, 185, 174));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/logoFinalRecortado.png"))); // NOI18N
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 130));

        btnGenerarReporte.setBackground(new java.awt.Color(207, 185, 174));
        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/pdfIcon2.png"))); // NOI18N
        btnGenerarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseClicked(evt);
            }
        });
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 140, 130));

        lblGenerarReporte1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblGenerarReporte1.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerarReporte1.setText("Generar Reporte");
        getContentPane().add(lblGenerarReporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 170, 30));

        cbxTipoInforme.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        cbxTipoInforme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reporte Lotes", "Reporte Empleados", "Reporte Final" }));
        getContentPane().add(cbxTipoInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 200, 40));

        lblFondo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/fondoReporte.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1370, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseClicked

        generarPDF();

    }//GEN-LAST:event_btnGenerarReporteMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        frmPrincipal myMain = new frmPrincipal();
        myMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void generarPDF() {
        
        String fechaInicioR = new SimpleDateFormat("dd/MM/yyyy").format(this.cldFechaInicio.getDate());
        String fechaFinR = new SimpleDateFormat("dd/MM/yyyy").format(this.cldFechaFin.getDate());
        Date startDate = this.cldFechaInicio.getDate();
        Date endDate = this.cldFechaFin.getDate();

        int informeLote = 0;
        int informeEmpleados = 0;
        int informeFinal = 0;
        
        if (this.cbxTipoInforme.getSelectedItem().toString() == "Reporte Lotes") {
            informeLote = 1;
        }
        if (this.cbxTipoInforme.getSelectedItem().toString() == "Reporte Empleados") {
            informeEmpleados = 1;
        }
        if (this.cbxTipoInforme.getSelectedItem().toString() == "Reporte Final") {
            informeFinal = 1;
        }
        
        if (this.cbxTipoInforme.getSelectedItem()=="") {
            JOptionPane.showMessageDialog(null,"Escoga un tipo de informe!");
            
        }
        //<editor-fold defaultstate="collapsed" desc="GENERAR REPORTES LOTES"> 
        if (informeLote == 1) {
            try {
                Document document = new Document(PageSize.LETTER, 30, 30, 30, 30);

                PdfWriter.getInstance(document, new FileOutputStream(FILE1));
                Font bfBold12 = new Font(FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(0, 0, 0));
                Font bf12 = new Font(FontFamily.TIMES_ROMAN, 12);
                document.open();
                //addMetaData(document);

                addTitlePage(document, fechaInicioR, fechaFinR);

                Paragraph parrafo5 = new Paragraph("------------------------------------------------------------------------------------------------------------------------------------");

                parrafo5.setAlignment(Element.ALIGN_LEFT);
                addEmptyLine(parrafo5, 1);

                document.add(parrafo5);

                float[] columnWidths = {1.5f, 3f, 3f, 4f,2f};
                PdfPTable tablaLotes = new PdfPTable(columnWidths);

                tablaLotes.addCell("FECHA");
                tablaLotes.addCell("NOMBRE EVENTO");
                tablaLotes.addCell("REALIZADA POR ");
                tablaLotes.addCell("DESCRIPCION");
                tablaLotes.addCell("COSTOS");
                
                tablaLotes.setWidthPercentage(100f);
                
                /* Create Connection objects */
                Class.forName("oracle.jdbc.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe", "ADMINCOFFE", "nelcy");
                Statement stmt = conn.createStatement();
                /* Define the SQL query */
                ResultSet query_set = stmt.executeQuery("SELECT EVEFECHA,EVENOMBRE,EMPNOMBRE, EVEDESCRIPCION,EVECOSTO FROM EVENTO inner join EMPLEADO on evento.empcedula=empleado.empcedula WHERE EVEFECHA between '" + fechaInicioR + "' and '" + fechaFinR + "' ");
                /* Step-2: Initialize PDF documents - logical objects */

                //we have four columns in our table
                float[] ancho = {1.5f, 3f, 3f, 4f,2f};
                PdfPTable my_report_table = new PdfPTable(ancho);
                my_report_table.setWidthPercentage(100f);

                //create a cell object
                PdfPCell table_cell;

                while (query_set.next()) {
                    String Fecha = query_set.getString("EVEFECHA");
                    table_cell = new PdfPCell(new Phrase(Fecha));
                    my_report_table.addCell(table_cell);
                    String Nombre = query_set.getString("EVENOMBRE");
                    table_cell = new PdfPCell(new Phrase(Nombre));
                    my_report_table.addCell(table_cell);
                    String Nombre_Empleado = query_set.getString("EMPNOMBRE");
                    table_cell = new PdfPCell(new Phrase(Nombre_Empleado));
                    my_report_table.addCell(table_cell);
                    String Descripcion = query_set.getString("EVEDESCRIPCION");
                    table_cell = new PdfPCell(new Phrase(Descripcion));
                    my_report_table.addCell(table_cell);
                    String Costo = query_set.getString("EVECOSTO");
                    table_cell = new PdfPCell(new Phrase(Costo));
                    my_report_table.addCell(table_cell);
                }
                /* Attach report table to PDF */
                document.add(tablaLotes);
                document.add(my_report_table);
                document.close();

                /* Close all DB related objects */
                query_set.close();
                stmt.close();
                conn.close();

                JOptionPane.showMessageDialog(null, "Reporte por lotes Generado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        //</editor-fold>
        
        
        //<editor-fold defaultstate="collapsed" desc="GENERAR REPORTES PARA EMPLEADOS"> 
        // DESDE AQUÍ CODIGO PARA GENERAR INFORMES POR EMPLEADOS , INCLUYE RECIBOS
          if (informeEmpleados == 1) {
            try {
                // Inicializamos el documento, definimos un tamaño de página, en este caso carta y luego los márgenes que se tendrán.
                Document document = new Document(PageSize.LETTER, 30, 30, 30, 30);

                // Se guarda el documento en la ruta que preincializamos previamente
                //TO DO buscar como se haría manualmente
                
                PdfWriter.getInstance(document, new FileOutputStream(FILE2));
                
                // Definimos algunos estilos de letra a usar
                Font bfBold12 = new Font(FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(0, 0, 0));
                Font bf12 = new Font(FontFamily.TIMES_ROMAN, 12);
                
                // Abrimos el documento para añadirle nuestro contenido
                document.open();
                //addMetaData(document);
                
                // En esta parte se le añade el título y la parte incial del informe

                addTitlePage2(document, fechaInicioR, fechaFinR);

                Paragraph parrafo5 = new Paragraph("------------------------------------------------------------------------------------------------------------------------------------");

                parrafo5.setAlignment(Element.ALIGN_LEFT);
                addEmptyLine(parrafo5, 1);

                document.add(parrafo5);
                
                // Definimos el tamaño de las columnas y por ender el número de columnas de nuestra tabla.

                float[] columnWidths = {1.5f, 5f, 5f, 2f};
                PdfPTable tablaLotes = new PdfPTable(columnWidths);

                tablaLotes.addCell("FECHA");
                tablaLotes.addCell("NOMBRE EMPLEADO");
                tablaLotes.addCell("DESCRIPCION");
                tablaLotes.addCell("COSTOS");

                tablaLotes.setWidthPercentage(100f);

                /* Create Connection objects */
                Class.forName("oracle.jdbc.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe", "ADMINCOFFE", "nelcy");
                Statement stmt = conn.createStatement();
                /* Define the SQL query */
                
                
                
                ResultSet query_set = stmt.executeQuery("select evefecha,empnombre,evedescripcion,evecosto from empleado inner join EVENTO on EMPLEADO.EMPCEDULA=EVENTO.EMPCEDULA  and lotcodigo=1  order by evefecha asc");
                /* Step-2: Initialize PDF documents - logical objects */

                //we have four columns in our table
                float[] ancho = {1.5f, 5f, 5f, 2f};
                PdfPTable my_report_table = new PdfPTable(ancho);
                my_report_table.setWidthPercentage(100f);

                //create a cell object
                PdfPCell table_cell;
                

                while (query_set.next()) {
                    String Fecha = query_set.getString("EVEFECHA");
                    table_cell = new PdfPCell(new Phrase(Fecha));
                    my_report_table.addCell(table_cell);
                    String Nombre = query_set.getString("EMPNOMBRE");
                    table_cell = new PdfPCell(new Phrase(Nombre));
                    my_report_table.addCell(table_cell);
                    String Descripcion = query_set.getString("EVEDESCRIPCION");
                    table_cell = new PdfPCell(new Phrase(Descripcion));
                    my_report_table.addCell(table_cell);
                    String Costo = query_set.getString("EVECOSTO");
                    table_cell = new PdfPCell(new Phrase(Costo));
                    my_report_table.addCell(table_cell);
                }
                /* Attach report table to PDF */
                document.add(tablaLotes);
                document.add(my_report_table);
                document.close();

                /* Close all DB related objects */
                query_set.close();
                stmt.close();
                conn.close();

                JOptionPane.showMessageDialog(null, "Reporte por Empleados Generado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
           //</editor-fold>
           
           
        //<editor-fold defaultstate="collapsed" desc="GENERAR REPORTE FINAL "> 
        
        // CODIGO PARA INFORME FINAL
          if (informeFinal == 1) {
            try {
                Document document = new Document(PageSize.LETTER, 30, 30, 30, 30);

                PdfWriter.getInstance(document, new FileOutputStream(FILE1));
                Font bfBold12 = new Font(FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(0, 0, 0));
                Font bf12 = new Font(FontFamily.TIMES_ROMAN, 12);
                document.open();
                //addMetaData(document);

                addTitlePage3(document, fechaInicioR, fechaFinR);

                Paragraph parrafo5 = new Paragraph("------------------------------------------------------------------------------------------------------------------------------------");

                parrafo5.setAlignment(Element.ALIGN_LEFT);
                addEmptyLine(parrafo5, 1);

                document.add(parrafo5);

                float[] columnWidths = {1.5f, 5f, 5f, 2f};
                PdfPTable tablaLotes = new PdfPTable(columnWidths);

                tablaLotes.addCell("FECHA");
                tablaLotes.addCell("NOMBRE EVENTO");
                tablaLotes.addCell("DESCRIPCION");
                tablaLotes.addCell("COSTOS");

                tablaLotes.setWidthPercentage(100f);

                /* Create Connection objects */
                Class.forName("oracle.jdbc.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe", "ADMINCOFFE", "nelcy");
                Statement stmt = conn.createStatement();
                /* Define the SQL query */
                ResultSet query_set = stmt.executeQuery("SELECT EVEFECHA,EVENOMBRE,EVEDESCRIPCION,EVECOSTO FROM EVENTO WHERE EVEFECHA between '" + fechaInicioR + "' and '" + fechaFinR + "' ");
                /* Step-2: Initialize PDF documents - logical objects */

                //we have four columns in our table
                float[] ancho = {1.5f, 5f, 5f, 2f};
                PdfPTable my_report_table = new PdfPTable(ancho);
                my_report_table.setWidthPercentage(100f);

                //create a cell object
                PdfPCell table_cell;
               // query_set.getArray()

                while (query_set.next()) {
                    String Fecha = query_set.getString("EVEFECHA");
                    table_cell = new PdfPCell(new Phrase(Fecha));
                    my_report_table.addCell(table_cell);
                    String Nombre = query_set.getString("EVENOMBRE");
                    table_cell = new PdfPCell(new Phrase(Nombre));
                    my_report_table.addCell(table_cell);
                    String Descripcion = query_set.getString("EVEDESCRIPCION");
                    table_cell = new PdfPCell(new Phrase(Descripcion));
                    my_report_table.addCell(table_cell);
                    String Costo = query_set.getString("EVECOSTO");
                    table_cell = new PdfPCell(new Phrase(Costo));
                    my_report_table.addCell(table_cell);
                }
                /* Attach report table to PDF */
                document.add(tablaLotes);
                document.add(my_report_table);
                document.close();

                /* Close all DB related objects */
                query_set.close();
                stmt.close();
                conn.close();

                JOptionPane.showMessageDialog(null, "Reporte por lotes Generado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
           //</editor-fold>
             
        
    }

    

    private void addTitlePage(Document document, String fechaInicioo, String fechaFinn) throws DocumentException, IOException {

        Image imagen = Image.getInstance("F:\\Andres Garzon\\universidad\\infoIII\\Final\\CoffeSoft\\CafeSoft\\CafeSoft_Jeison\\CafeSoft_V1.4\\CafeSoft\\src\\PRESENTACION\\imagenes\\logoFinalRecortado.png");
        imagen.setAbsolutePosition(0f, 650f);
        document.add(imagen);
        Paragraph parrafo1 = new Paragraph("Reporte LOTES");

        Paragraph parrafo2 = new Paragraph("FINCA LA CORONA");

        parrafo1.setAlignment(Element.ALIGN_CENTER);
        parrafo1.setFont(subFont);
        parrafo2.setFont(catFont);
        addEmptyLine(parrafo1, 1);
        document.add(parrafo1);
        parrafo2.setAlignment(Element.ALIGN_CENTER);
        addEmptyLine(parrafo2, 1);
        document.add(parrafo2);

        Paragraph parrafo3 = new Paragraph("Este documento describe las actividades realizadas entre :   ", smallBold);
        parrafo3.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo3);

        Paragraph parrafo4 = new Paragraph("" + fechaInicioo + " y " + fechaFinn, smallBold);
        parrafo4.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo4);

        Paragraph parrafo5 = new Paragraph("Este reporte fue creado por: ....Coffe Soft - Su café al máximo.... ");

        parrafo5.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo5);

    }
    private void addTitlePage2(Document document, String fechaInicioo, String fechaFinn) throws DocumentException, IOException {

        Image imagen = Image.getInstance("F:\\Andres Garzon\\universidad\\infoIII\\Final\\CoffeSoft\\CafeSoft\\CafeSoft_Jeison\\CafeSoft_V1.4\\CafeSoft\\src\\PRESENTACION\\imagenes\\logoFinalRecortado.png");
        imagen.setAbsolutePosition(0f, 650f);
        document.add(imagen);
        Paragraph parrafo1 = new Paragraph("REPORTE EMPLEADOS ");

        Paragraph parrafo2 = new Paragraph("FINCA LA CORONA");

        parrafo1.setAlignment(Element.ALIGN_CENTER);
        parrafo1.setFont(subFont);
        parrafo2.setFont(catFont);
        addEmptyLine(parrafo1, 1);
        document.add(parrafo1);
        parrafo2.setAlignment(Element.ALIGN_CENTER);
        addEmptyLine(parrafo2, 1);
        document.add(parrafo2);

        Paragraph parrafo3 = new Paragraph("Este documento describe los saldos a pagar de los empleados entre  :   ", smallBold);
        parrafo3.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo3);

        Paragraph parrafo4 = new Paragraph("" + fechaInicioo + " y " + fechaFinn, smallBold);
        parrafo4.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo4);

        Paragraph parrafo5 = new Paragraph("Este reporte fue creado por: ....Coffe Soft - Su café al máximo.... ");

        parrafo5.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo5);

    }
    private void addTitlePage3(Document document, String fechaInicioo, String fechaFinn) throws DocumentException, IOException {

        Image imagen = Image.getInstance("F:\\Andres Garzon\\universidad\\infoIII\\Final\\CoffeSoft\\CafeSoft\\CafeSoft_Jeison\\CafeSoft_V1.4\\CafeSoft\\src\\PRESENTACION\\imagenes\\logoFinalRecortado.png");
        imagen.setAbsolutePosition(0f, 650f);
        document.add(imagen);
        Paragraph parrafo1 = new Paragraph("REPORTE FINAL");

        Paragraph parrafo2 = new Paragraph("FINCA LA CORONA");

        parrafo1.setAlignment(Element.ALIGN_CENTER);
        parrafo1.setFont(subFont);
        parrafo2.setFont(catFont);
        addEmptyLine(parrafo1, 1);
        document.add(parrafo1);
        parrafo2.setAlignment(Element.ALIGN_CENTER);
        addEmptyLine(parrafo2, 1);
        document.add(parrafo2);

        Paragraph parrafo3 = new Paragraph("Este documento describe un informe final para la finca! Aquí se sabrá si su cosecha e inversión dieron resultados favorables o no. :   ", smallBold);
        parrafo3.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo3);

        Paragraph parrafo4 = new Paragraph("" + fechaInicioo + " y " + fechaFinn, smallBold);
        parrafo4.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo4);

        Paragraph parrafo5 = new Paragraph("Este reporte fue creado por: ....Coffe Soft - Su café al máximo.... ");

        parrafo5.setAlignment(Element.ALIGN_CENTER);

        document.add(parrafo5);

    }

 

    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnHome;
    private javax.swing.JComboBox<String> cbxTipoInforme;
    private com.toedter.calendar.JDateChooser cldFechaFin;
    private com.toedter.calendar.JDateChooser cldFechaInicio;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGenerarReporte1;
    private javax.swing.JLabel lblParametros;
    // End of variables declaration//GEN-END:variables

    private void setIcon2() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconProgram.png")));
    }
}
