/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

import NEGOCIO.Administrador;
import NEGOCIO.Empleado;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author NELCY
 */
public class frmRegistrarEmpleado extends javax.swing.JFrame {
    Empleado miEmpleado;
    Administrador miAdmin;
    long vCedulaEmpleado;
    
    Toolkit t;
    Dimension screenSize;
    ImageIcon fot;
    ImageIcon fot2;
    Icon icono;
    Icon icono2;
    
    /**
     * Creates new form frmRegistrarEmpleado
     */
    public frmRegistrarEmpleado() {
        initComponents();
        miEmpleado = new Empleado();
        miAdmin = new Administrador();
        
        vCedulaEmpleado = 0;
        this.tblEscondidaEmp.setVisible(false);
        this.lblNotificacionCedula.setVisible(false);
        solonumeros(this.txtBuscarCedula);
        solonumeros(this.txtCedula);
        solonumeros(this.txtCelular);
        solonumeros(this.txtEdad);
        sololetras(this.txtApellidos);
        sololetras(this.txtBuscarNombre);
        sololetras(this.txtNombres);
        
        setLocationRelativeTo(frmRegistrarEmpleado.this);        // Centering on screen...
        setTitle("GESTION DE PERSONAS"); 
        //setSize(1370, 600);                  // Setting dimensions...
        this.setExtendedState(frmRegistrarEmpleado.MAXIMIZED_BOTH);
        setIcon();
        
        
        
        t = Toolkit.getDefaultToolkit();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        
        fot = new ImageIcon("src/PRESENTACION/imagenes/coffe wall 1.jpg");
        icono = new ImageIcon(fot.getImage().getScaledInstance(this.lblFondo.getWidth(), this.lblFondo.getHeight(), Image.SCALE_DEFAULT));
        this.lblFondo.setIcon(icono);
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblBuscarCedula = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNotificacionCedula = new javax.swing.JLabel();
        lblBuscarNombre = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        JScrollPane1 = new javax.swing.JScrollPane();
        tblListarEmp = new javax.swing.JTable();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtBuscarCedula = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtBuscarNombre = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEscondidaEmp = new javax.swing.JTable();

        jLabel1.setBackground(new java.awt.Color(153, 51, 0));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("BackgroundImageLabel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCelular.setFont(new java.awt.Font("Century", 1, 22)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("CELULAR : ");
        lblCelular.setToolTipText("");
        getContentPane().add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, -1));

        lblApellidos.setFont(new java.awt.Font("Century", 1, 22)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("*APELLIDOS :");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, -1));

        lblBuscarCedula.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        lblBuscarCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarCedula.setText("CÉDULA ");
        getContentPane().add(lblBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, -1, -1));

        lblNombres.setFont(new java.awt.Font("Century", 1, 22)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("*NOMBRES : ");
        getContentPane().add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, -1));

        lblEdad.setFont(new java.awt.Font("Century", 1, 22)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(255, 255, 255));
        lblEdad.setText("EDAD : ");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 111, -1));

        lblCedula.setFont(new java.awt.Font("Century", 1, 22)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("*CEDULA :");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        lblNotificacionCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNotificacionCedula.setForeground(new java.awt.Color(240, 240, 240));
        lblNotificacionCedula.setText("Cédula ya existe!");
        getContentPane().add(lblNotificacionCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        lblBuscarNombre.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblBuscarNombre.setForeground(new java.awt.Color(240, 240, 240));
        lblBuscarNombre.setText("NOMBRE");
        getContentPane().add(lblBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 100, 30));

        btnBorrar.setBackground(new java.awt.Color(113, 52, 15));
        btnBorrar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/delete 32.png"))); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(null);
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 150, 60));

        btnListar.setBackground(new java.awt.Color(113, 52, 15));
        btnListar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/listar.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.setBorder(null);
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 150, 60));

        btnEditar.setBackground(new java.awt.Color(113, 52, 15));
        btnEditar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(null);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 150, 60));

        btnGuardar.setBackground(new java.awt.Color(113, 52, 15));
        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 150, 60));

        btnHome.setBackground(new java.awt.Color(243, 218, 206));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/logoFinalRecortado.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 140));

        tblListarEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblListarEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListarEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListarEmpMouseClicked(evt);
            }
        });
        JScrollPane1.setViewportView(tblListarEmp);

        getContentPane().add(JScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 1250, 280));

        txtNombres.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 450, 30));

        txtApellidos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 450, 30));

        txtEdad.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 120, 30));

        txtCelular.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 450, 30));

        txtBuscarCedula.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        txtBuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCedulaKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 270, 30));

        txtCedula.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 450, 30));

        txtBuscarNombre.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        txtBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarNombreKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 270, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        tblEscondidaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblEscondidaEmp);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 1250, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Eventos">
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int veriCampos = verificarCampos();
        if (veriCampos == 0){
            long cedula = Long.valueOf(this.txtCedula.getText());

            String nombres = this.txtNombres.getText();
            String apellidos = this.txtApellidos.getText();
            long telefono = Long.valueOf(this.txtCelular.getText());
            int edad = Integer.parseInt(this.txtEdad.getText());
            //Date fecha = Date.valueOf(this.txtFechaNac.getText());
            //String fechaStr = new SimpleDateFormat("dd-MM-yyyy").format(fecha);
            int res = miAdmin.registrarEmpleados(cedula, nombres.toLowerCase(), apellidos.toLowerCase(), edad, telefono);
            if (res == 1) {
                JOptionPane.showMessageDialog(this, "Registro exitoso");
                limpiar();
                listar();
                vCedulaEmpleado = 0;
            } else {
                JOptionPane.showMessageDialog(this, "Registro no exitoso");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Datos Obligatorios (**) sin llenar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        // TODO add your handling code here:
        
        
        int fila = this.tblListarEmp.getSelectedRow();
        int checkBusqueda= buscarEnEventoEmpleadoCedula(vCedulaEmpleado);
        if (fila != -1) 
        {
             if(checkBusqueda == 1){
                    long cedulaEliminar = Long.parseLong(this.tblListarEmp.getValueAt(fila, 0).toString());
                    int res = miAdmin.eliminarEmpleados(cedulaEliminar);
                    if (res != 0) {
                        JOptionPane.showMessageDialog(rootPane, "Encargado eliminado con éxito");
                        listar();
                        limpiar();
                        vCedulaEmpleado = 0;
                        
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Encargado no eliminado");
                    }
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "El encargado esta relacionado con alguno(s) actividades registradas");            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro para eliminar");
        }
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void txtBuscarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarNombreKeyReleased
        // TODO add your handling code here:
        String bNombree = this.txtBuscarNombre.getText();
        buscarEmpleadoNombre(bNombree.toLowerCase());
        
        
    }//GEN-LAST:event_txtBuscarNombreKeyReleased

    private void txtBuscarCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCedulaKeyReleased
        // TODO add your handling code here:
        long cedulaB = 0;
        if(this.txtBuscarCedula.getText().length() == 0)
            cedulaB = 0;
        else
            cedulaB = Long.parseLong(this.txtBuscarCedula.getText());
        buscarEmpleadoCedula(cedulaB);     
    }//GEN-LAST:event_txtBuscarCedulaKeyReleased

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        // TODO add your handling code here:
        long bCedula = 0;
        if(this.txtCedula.getText().length() == 0)
            bCedula = 0;
        else
            bCedula = Long.parseLong(this.txtCedula.getText());
        
        miEmpleado.setCedula(bCedula);
        int checkBusqueda= buscar(bCedula);
        
        if(checkBusqueda == 1){
            this.lblNotificacionCedula.setVisible(false);
            this.btnGuardar.setEnabled(true);
        }else{
            this.lblNotificacionCedula.setVisible(true);
            this.btnGuardar.setEnabled(false);
        }
            
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        int fila = this.tblListarEmp.getSelectedRow();
        int veriCampos = verificarCampos();
        if (fila != -1) 
        {
            if (veriCampos == 0){
            
                long cedula = Long.parseLong(this.txtCedula.getText());
                String nombres = this.txtNombres.getText();
                String apellidos = this.txtApellidos.getText();
                int edad = Integer.parseInt(this.txtEdad.getText());
                long telefono = Long.parseLong(this.txtCelular.getText());

                int res = miAdmin.actualizarEmpleados(cedula, nombres.toLowerCase(), apellidos.toLowerCase(), edad, telefono);
                if (res != 0) {

                    JOptionPane.showMessageDialog(rootPane, "Empleado actualizado con éxito");
                    listar();
                    limpiar();
                    vCedulaEmpleado = 0;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Empleado no actualizado");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Datos Obligatorios (**) sin llenar");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro para eliminar");
            listar();
        }
        
    }//GEN-LAST:event_btnEditarMouseClicked

    private void tblListarEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListarEmpMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int fila = this.tblListarEmp.getSelectedRow();
        vCedulaEmpleado = Integer.parseInt(this.tblListarEmp.getValueAt(fila, 0).toString());

        this.txtCedula.setText(this.tblListarEmp.getValueAt(fila, 0).toString());
        this.txtNombres.setText(this.tblListarEmp.getValueAt(fila, 1).toString());
        this.txtApellidos.setText(this.tblListarEmp.getValueAt(fila, 2).toString());
        this.txtEdad.setText(this.tblListarEmp.getValueAt(fila, 3).toString());
        this.txtCelular.setText(this.tblListarEmp.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tblListarEmpMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        frmPrincipal myPrincipal = new frmPrincipal();
        myPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeMouseClicked
    //</editor-fold> 

    //<editor-fold defaultstate="collapsed" desc="Excepciones">
    public  void  solonumeros(JTextField a){
       a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c=e.getKeyChar();
            if(Character.isLetter(c)){
                getToolkit().beep();
                e.consume();
            }
        }  
           
       });
    }
    
    public  void  sololetras(JTextField a){
       a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c=e.getKeyChar();
            if(Character.isDigit(c)){
                getToolkit().beep();
                e.consume();
            }
        }  
           
       });
    }
    
    //</editor-fold>     
 
    //<editor-fold defaultstate="collapsed" desc="Metodos Propios">
    private void bloquear(){
        this.txtApellidos.setEnabled(false);
        this.txtBuscarCedula.setEnabled(false);
        this.txtCedula.setEnabled(false);
        this.txtCelular.setEnabled(false);
        this.txtEdad.setEnabled(false);
        this.txtNombres.setEnabled(false);
    }
    private void desbloquear(){
        this.txtApellidos.setEnabled(true);
        this.txtBuscarCedula.setEnabled(true);
        this.txtCedula.setEnabled(true);
        this.txtCelular.setEnabled(true);
        this.txtEdad.setEnabled(true);
        this.txtNombres.setEnabled(true);
    }
    
    private int verificarCampos(){
        int retVerificar = 0;
        
        if(this.txtCedula.getText().length()==0)
            retVerificar = 1;
        if(this.txtNombres.getText().length()==0)
            retVerificar = 1;
        if(this.txtApellidos.getText().length()==0)
            retVerificar = 1;
        
        return retVerificar;    
    }
    
    private void buscarEmpleadoCedula(long bCedula) {
        
        
        
        ArrayList<Object[]> empleados = miAdmin.buscarEmpleadosCedulaDigitando(bCedula);
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListarEmp.setModel(datos);

        Object[] columnas = empleados.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < empleados.size(); i++) {
            datos.addRow(empleados.get(i));
        }
        
    }
    
    private void buscarEmpleadoNombre(String bNombree) {
        
        
        
        ArrayList<Object[]> empleados = miAdmin.buscarEmpleadosNombre(bNombree.toLowerCase());
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListarEmp.setModel(datos);

        Object[] columnas = empleados.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < empleados.size(); i++) {
            datos.addRow(empleados.get(i));
        }
        
    }
    
    private int buscarEnEventoEmpleadoCedula(long vcedula) {
        
        
        
        ArrayList<Object[]> empleados = miAdmin.buscarEnEventoEmpleadoCed(vcedula);
        DefaultTableModel datos = new DefaultTableModel();
        this.tblEscondidaEmp.setModel(datos);

        Object[] columnas = empleados.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < empleados.size(); i++) {
            datos.addRow(empleados.get(i));
        }
        if (tblEscondidaEmp.getRowCount() == 0)
            return 1;
        else 
            return 0; 
        
    }
    
    private int buscar(long bCedula) {
        
        ArrayList<Object[]> empleados = miAdmin.buscarEmpleadosCedula(bCedula);
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListarEmp.setModel(datos);

        Object[] columnas = empleados.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < empleados.size(); i++) {
            datos.addRow(empleados.get(i));
        }
        if (tblListarEmp.getRowCount() == 0)
            return 1;
        else 
            return 0;  

    }

    private void limpiar() {

        this.txtCedula.setText("");
        this.txtNombres.setText("");
        this.txtApellidos.setText("");
        this.txtBuscarCedula.setText("");
        this.txtEdad.setText("");
        this.txtCelular.setText("");

    }

    private void listar() {

        ArrayList<Object[]> empleados = miAdmin.listarEmpleados();
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListarEmp.setModel(datos);

        Object[] columnas = empleados.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < empleados.size(); i++) {
            datos.addRow(empleados.get(i));
        }
    }
    
    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconProgram.png")));
    }
    //</editor-fold> 
    
    //<editor-fold defaultstate="collapsed" desc="Main">
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblBuscarCedula;
    private javax.swing.JLabel lblBuscarNombre;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNotificacionCedula;
    private javax.swing.JTable tblEscondidaEmp;
    private javax.swing.JTable tblListarEmp;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscarCedula;
    private javax.swing.JTextField txtBuscarNombre;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
    
}
//</editor-fold>