/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

import NEGOCIO.Administrador;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SGTheDreamer
 */
public class frmRegistrarLote extends javax.swing.JFrame {
    Administrador miAdmin; 
    int vCodLote;
    
    Toolkit t;
    Dimension screenSize;
    ImageIcon fot;
    ImageIcon fot2;
    Icon icono;
    Icon icono2;
    
    /**
     * Creates new form frmRegistrarLote
     */
    public frmRegistrarLote() {
        miAdmin = new Administrador();
        initComponents();
        
        Calendar c2 = new GregorianCalendar();
        this.cldFechaSiembra.setCalendar(c2);
        solonumeros(this.txtCodigo);
        solonumeros(this.txtNArbolesCafe);
        solonumeros(this.txtNArbolesSombra);
        vCodLote = 0;
        this.lblNotificacionNombre.setVisible(false);
        this.tblEscondida.setVisible(false);
        
        setLocationRelativeTo(frmRegistrarLote.this);        // Centering on screen...
        setTitle("GESTION DE LOTES"); 
        //setSize(1370, 600);                  // Setting dimensions...
        this.setExtendedState(frmRegistrarLote.MAXIMIZED_BOTH);
        setIcon();
        
        
        
        t = Toolkit.getDefaultToolkit();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        
        fot = new ImageIcon("src/PRESENTACION/imagenes/coffe_wall3.jpg");
        icono = new ImageIcon(fot.getImage().getScaledInstance(this.lblFondo.getWidth(), this.lblFondo.getHeight(), Image.SCALE_DEFAULT));
        this.lblFondo.setIcon(icono);
        this.repaint();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrincipal = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblNArbolesCafe = new javax.swing.JLabel();
        lblFechaSiembra = new javax.swing.JLabel();
        lblNArbolesSombra = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNotaBuscar = new javax.swing.JLabel();
        lblNotificacionNombre = new javax.swing.JLabel();
        lblBuscarNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNArbolesCafe = new javax.swing.JTextField();
        txtNArbolesSombra = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaUbicacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        cldFechaSiembra = new com.toedter.calendar.JDateChooser();
        txtBuscarNombre = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEscondida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/logoFinalRecortado.png"))); // NOI18N
        btnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseClicked(evt);
            }
        });
        getContentPane().add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/guardar_48.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, 60));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/update_48.png"))); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 70, 60));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/delete_48.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 70, 60));

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRESENTACION/imagenes/listar_48.png"))); // NOI18N
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 90, 60));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("*Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblUbicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        lblUbicacion.setText("*Ubicación:");
        getContentPane().add(lblUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        lblNArbolesCafe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNArbolesCafe.setForeground(new java.awt.Color(255, 255, 255));
        lblNArbolesCafe.setText("*Nº Àrboles Cafè: ");
        getContentPane().add(lblNArbolesCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblFechaSiembra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaSiembra.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaSiembra.setText("Fecha Siembra:");
        getContentPane().add(lblFechaSiembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lblNArbolesSombra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNArbolesSombra.setForeground(new java.awt.Color(255, 255, 255));
        lblNArbolesSombra.setText("Nº Àrboles Sombra:");
        getContentPane().add(lblNArbolesSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código:");
        lblCodigo.setToolTipText("");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        lblNotaBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNotaBuscar.setForeground(new java.awt.Color(240, 240, 240));
        lblNotaBuscar.setText("Buscar");
        getContentPane().add(lblNotaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        lblNotificacionNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNotificacionNombre.setForeground(new java.awt.Color(240, 240, 240));
        lblNotificacionNombre.setText("El nombre ya se encuentra!");
        getContentPane().add(lblNotificacionNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        lblBuscarNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBuscarNombre.setForeground(new java.awt.Color(240, 240, 240));
        lblBuscarNombre.setText("Nombre:");
        getContentPane().add(lblBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 200, -1));

        txtNArbolesCafe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtNArbolesCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, -1));

        txtNArbolesSombra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtNArbolesSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 100, -1));

        txtaUbicacion.setColumns(20);
        txtaUbicacion.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtaUbicacion.setRows(5);
        jScrollPane1.setViewportView(txtaUbicacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 350, 80));

        tblListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 1260, 250));

        cldFechaSiembra.setDateFormatString("dd-MM-yyyy");
        cldFechaSiembra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cldFechaSiembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 200, 30));

        txtBuscarNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarNombreKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 100, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        tblEscondida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblEscondida);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 1260, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="Eventos">
    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        
        int veriCampos = verificarCampos();
        
        if (veriCampos == 0){
            String nombres = this.txtNombre.getText();
            String ubicacion = this.txtaUbicacion.getText();
            int nArbolesC = Integer.parseInt(this.txtNArbolesCafe.getText());
            String fechaS = new SimpleDateFormat("dd/MM/yyyy").format(this.cldFechaSiembra.getDate());
            int nArbolesS = Integer.parseInt(this.txtNArbolesSombra.getText());

            int res = miAdmin.registrarLote(nombres.toLowerCase(),ubicacion.toLowerCase(),nArbolesC, fechaS, nArbolesS);
            if(res == 1){
                JOptionPane.showMessageDialog(this, "Registro exitoso");
                limpiar();
                listar();
                vCodLote = 0;
                this.txtCodigo.setEnabled(true);
            }            
            else
            JOptionPane.showMessageDialog(this, "Registro no exitoso");
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Datos Obligatorios (**) sin llenar");
        }
        
        
        
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:

        int veriCampos = verificarCampos();
        if (vCodLote != 0){
            
            if (veriCampos == 0){
                
                String nombres = this.txtNombre.getText();
                String ubicacion = this.txtaUbicacion.getText();
                int nArbolesC = Integer.parseInt(this.txtNArbolesCafe.getText());
                String fechaS = new SimpleDateFormat("dd/MM/yyyy").format(this.cldFechaSiembra.getDate());
                int nArbolesS = Integer.parseInt(this.txtNArbolesSombra.getText());
                int codigo = Integer.parseInt(this.txtCodigo.getText());

                int res = miAdmin.actualizarLote(nombres.toLowerCase(),ubicacion.toLowerCase(),nArbolesC,fechaS,nArbolesS,codigo);

                if (res == 1) {
                    JOptionPane.showMessageDialog(this, "Lote Actualizado");
                    limpiar();
                    listar();
                    vCodLote = 0;
                    this.txtCodigo.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Lote NO Actualizado");
                }
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Datos Obligatorios (**) sin llenar");
            }
            
        }else
            JOptionPane.showMessageDialog(this, "Seleccione un registro!");
        
        
        

    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:

        int fila = this.tblListar.getSelectedRow();
        int checkBusqueda= buscarEnEventoLoteCodigo(vCodLote);
        if(fila != -1)
        {

            if(checkBusqueda == 1){

                int codEliminar = Integer.parseInt(this.tblListar.getValueAt(fila,0).toString());
                int res = miAdmin.eliminarLote(codEliminar);
                if(res!=0){
                    JOptionPane.showMessageDialog(rootPane, "Lote eliminado con éxito");

                    listar();
                    limpiar();
                    vCodLote = 0;
                    this.txtCodigo.setEnabled(true);
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Lote no eliminado");
            }
            else
                JOptionPane.showMessageDialog(rootPane, "El lote esta relacionado con alguno(s) actividades registradas");

        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro para eliminar");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnListarMouseClicked

    private void tblListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListarMouseClicked
        // TODO add your handling code here:
        this.txtCodigo.setEnabled(false);
        limpiar();
        int fila = this.tblListar.getSelectedRow();
        if (this.tblListar.getValueAt(fila,0).toString().length() == 0)
            vCodLote = 0;
        else
            vCodLote = Integer.parseInt(this.tblListar.getValueAt(fila,0).toString());
        this.txtCodigo.setText(this.tblListar.getValueAt(fila,0).toString());
        this.txtNombre.setText(this.tblListar.getValueAt(fila,1).toString());
        this.txtaUbicacion.setText(this.tblListar.getValueAt(fila,2).toString());
        this.txtNArbolesCafe.setText(this.tblListar.getValueAt(fila,3).toString());

        //String fechaList = this.tblListar.getValueAt(fila,4).toString();
        //this.cldFechaSiembra.setDateFormatString(fechaList.substring(0, 11));
        this.txtNArbolesSombra.setText(this.tblListar.getValueAt(fila,5).toString());

    }//GEN-LAST:event_tblListarMouseClicked

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
        int codigoo = 0;
        if(this.txtCodigo.getText().length() == 0)
            codigoo = 0;
        else
            codigoo = Integer.parseInt(this.txtCodigo.getText());
        buscarCodigo(codigoo);
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtBuscarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarNombreKeyReleased
        // TODO add your handling code here:
        String bNombree = this.txtBuscarNombre.getText();
        buscarNombre(bNombree.toLowerCase());
    }//GEN-LAST:event_txtBuscarNombreKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        String bNombree = this.txtNombre.getText();
        int checkBusqueda= buscarNombreCompleto(bNombree.toLowerCase());
        
        if(checkBusqueda == 1){
            this.lblNotificacionNombre.setVisible(false);
            this.btnGuardar.setEnabled(true);
        }    
        else{
            this.lblNotificacionNombre.setVisible(true);
            this.btnGuardar.setEnabled(false);
        }
            
        
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseClicked
        // TODO add your handling code here:
        frmPrincipal myPrincipal = new frmPrincipal();
        myPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPrincipalMouseClicked
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Excepciones">
    public  void  solonumeros(JTextField a){
       a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c=e.getKeyChar();
            if(Character.isLetter(c)){
                getToolkit().beep();
                e.consume();
            }
        }  
           
       });
    }
    
    public  void  sololetras(JTextField a){
       a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c=e.getKeyChar();
            if(Character.isDigit(c)){
                getToolkit().beep();
                e.consume();
            }
        }  
           
       });
    }
    
    //</editor-fold>    
    
    //<editor-fold defaultstate="collapsed" desc="Metodos Propios">
    private void bloquear(){
        this.txtBuscarNombre.setEnabled(false);
        this.txtCodigo.setEnabled(false);
        this.txtNArbolesCafe.setEnabled(false);
        this.txtNArbolesSombra.setEnabled(false);
        this.txtNombre.setEnabled(false);
        this.txtaUbicacion.setEnabled(false);
        this.cldFechaSiembra.setEnabled(false);
    }
    
    private void desbloquear(){
        this.txtBuscarNombre.setEnabled(true);
        this.txtCodigo.setEnabled(true);
        this.txtNArbolesCafe.setEnabled(true);
        this.txtNArbolesSombra.setEnabled(true);
        this.txtNombre.setEnabled(true);
        this.txtaUbicacion.setEnabled(true);
        this.cldFechaSiembra.setEnabled(true);
    }
    
    private void setIcon() {
    
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconProgram.png")));
        
    }
    
    private int verificarCampos(){
        int retVerificar = 0;
        
        if(this.txtNombre.getText().length()==0)
            retVerificar = 1;
        if(this.txtNArbolesCafe.getText().length()==0)
            retVerificar = 1;
        if(this.txtaUbicacion.getText().length()==0)
            retVerificar = 1;
        
        return retVerificar;    
    }
    
    private void buscarCodigo(int codigo) {
        
        
        
        ArrayList<Object[]> Lotes = miAdmin.buscarLoteCodigoCompleto(codigo);
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListar.setModel(datos);

        Object[] columnas = Lotes.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < Lotes.size(); i++) {
            datos.addRow(Lotes.get(i));
        }

        /*
        repaint1();
        repaint2();
        repaint3();
        repaint4();
        repaint5();
        repaint6();
        resizeColumnWidth(this.tblEscondida);
        */
        
    }
    
    private int buscarEnEventoLoteCodigo(int codigo) {
        
        
        
        ArrayList<Object[]> Lotes = miAdmin.buscarEnEventoLoteCod(codigo);
        DefaultTableModel datos = new DefaultTableModel();
        this.tblEscondida.setModel(datos);

        Object[] columnas = Lotes.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < Lotes.size(); i++) {
            datos.addRow(Lotes.get(i));
        }
        /*
        repaint1();
        repaint2();
        repaint3();
        repaint4();
        repaint5();
        repaint6();
        resizeColumnWidth(this.tblEscondida);
        */
        
        if (tblEscondida.getRowCount() == 0)
            return 1;
        else 
            return 0; 
        
    }
    
    private void buscarNombre(String bNombree) {
        
        
        
        ArrayList<Object[]> lotes = miAdmin.buscarLotesNombre(bNombree.toLowerCase());
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListar.setModel(datos);

        Object[] columnas = lotes.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < lotes.size(); i++) {
            datos.addRow(lotes.get(i));
        }

        /*
        repaint1();
        repaint2();
        repaint3();
        repaint4();
        repaint5();
        repaint6();
        resizeColumnWidth(this.tblEscondida);
        */
        
        
    }
    
    private int buscarNombreCompleto(String bNombree) {
        
        
        
        ArrayList<Object[]> lotes = miAdmin.buscarLotesNombreCompleto(bNombree.toLowerCase());
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListar.setModel(datos);

        Object[] columnas = lotes.get(0);
        for (int i = 0; i < columnas.length; i++) {
            datos.addColumn(columnas[i]);
        }
        for (int i = 1; i < lotes.size(); i++) {
            datos.addRow(lotes.get(i));
        }

        /*
        repaint1();
        repaint2();
        repaint3();
        repaint4();
        repaint5();
        repaint6();
        resizeColumnWidth(this.tblEscondida);
        */
        
        if (tblListar.getRowCount() == 0)
            return 1;
        else 
            return 0;       
        
    }
    
    private void limpiar(){
        this.txtNombre.setText("");
        this.txtaUbicacion.setText("");        
        this.txtCodigo.setText("");
        this.txtNArbolesCafe.setText("");
        this.txtNArbolesSombra.setText("");
        //this.cldFechaSiembra.cleanup();
    }
    
    private void listar(){   
        
        ArrayList<Object[]> lotes = miAdmin.listarLotes();
        DefaultTableModel datos = new DefaultTableModel();
        this.tblListar.setModel(datos);
        
        Object[] columnas = lotes.get(0);
        for(int i=0; i<columnas.length; i++)
            datos.addColumn(columnas[i]);
        for(int i=1; i<lotes.size(); i++)
            datos.addRow(lotes.get(i));  
        
        /*
        repaint1();
        repaint2();
        repaint3();
        repaint4();
        repaint5();
        repaint6();
        resizeColumnWidth(this.tblEscondida);
        */
        
        if (tblListar.getRowCount() == 0)
            JOptionPane.showMessageDialog(this, "No existen lotes registrados");
    }
    
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Main">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPrincipal;
    private com.toedter.calendar.JDateChooser cldFechaSiembra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBuscarNombre;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFechaSiembra;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNArbolesCafe;
    private javax.swing.JLabel lblNArbolesSombra;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNotaBuscar;
    private javax.swing.JLabel lblNotificacionNombre;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JTable tblEscondida;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txtBuscarNombre;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNArbolesCafe;
    private javax.swing.JTextField txtNArbolesSombra;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaUbicacion;
    // End of variables declaration//GEN-END:variables

}
 //</editor-fold>